### ISSUE TITLE
fix unavailable video in Project Directory section

### ISSUE THREAD

**Issue by smobregon** [bhdirect-ebooks/dev-docs#110]
Project scaffolding video is unavailable. 

Either update video link or create and add a new video including more recent updates and remove the 'Changes since video' list.

[Project Scaffolding](https://style.bhdirect-ebooks.org/process/proj_scaffold.html)

**Comment by flintsteel7** [comment]
- [ ] Peter (or someone?) record new video
- [ ] Savannah edit page once new video is available

**Comment by flintsteel7** [comment]
Here's the link to the new video:
`https://youtu.be/RDhEy5iD6i8`

I'd also like to change the order of the points under "Usage info" at the bottom of the page to:
- Clone your project repo.
- `cd` into the project folder and enter `start-project` The script will prompt you for some info and return some important project information.
- Create the **src** directory and add the source files to it.
