### ISSUE TITLE
combine abbreviations sections

### ISSUE THREAD

**Issue by sarah-bowe** [bhdirect-ebooks/dev-docs#112]
Move the following information on [this](https://style.bhdirect-ebooks.org/code/general_types.html#Abbreviations) page to be with the other abbreviation/glossary content on [this](https://style.bhdirect-ebooks.org/code/structural_types.html#Abbreviations-and-Glossaries) page.

![Screen Shot 2020-04-05 at 1 05 57 PM](https://user-images.githubusercontent.com/26905095/78505045-b4031500-773e-11ea-94c8-9e8c1dbc9b31.png)

**Comment by flintsteel7** [comment]
- [ ] copy code snippet to [Abbreviation Terms](https://style.bhdirect-ebooks.org/code/structural_types.html#Abbreviation-Terms) in Structural Types
- [ ] add a link in [General Types: Abbreviations](https://style.bhdirect-ebooks.org/code/general_types.html#Abbreviations) to [Structural Types: Abbreviations and Glossaries](https://style.bhdirect-ebooks.org/code/structural_types.html#Abbreviations-and-Glossaries)
