### ISSUE TITLE
add more misc. code examples of commonly found non-standard styles

### ISSUE THREAD

**Issue by marvinsmith4** [bhdirect-ebooks/dev-docs#117]
Add code examples of what we've done in the past with non-standard style issues.

**Comment by flintsteel7** [comment]
- Step 1: Gather data
  - [ ] (Peter) download slack history (as much of it as we can get)
  - [ ] perform searches on slack to find relevant info
- Step 2: Identify what to add and where
  - [ ] create individual issues where necessary
