### ISSUE TITLE
Add information for adding <a data-link='{"book":"0-19768","page":"page3"}'> markup

### ISSUE THREAD

**Issue by smobregon** [bhdirect-ebooks/dev-docs#138]
Find cross id from metadata and page number to link to existing vols

**Comment by flintsteel7** [comment]
Two different syntaxes work for creating links to other CROSS books:

`<a data-link='{"pub":"0","book":"19768","bookmark":"page3"}'>`
- "pub" is the CROSS ID number before the `-` (0 for Wordsearch)
- "book" is the CROSS ID portion after the `-`
- "bookmark" is the `id` attribute of the tag at the position to link to (will be converted to a `name` attribute by **epub2cross**)

`<a data-link='{"book":"0-19768","page":"page3"}'>`
- "book" is the CROSS ID (only works with `0-` IDs)
- "page" is the `id` attribute of the tag at the position to link to (will be converted to `name` attribute by **epub2cross**).
  - "page", doesn't technically have to be a page id. any `id` will work.

**Comment by flintsteel7** [comment]
Oh, this should probably go on the [Data Types](https://style.bhdirect-ebooks.org/code/data_types.html) page
